version: 0.2



phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 730365821560.dkr.ecr.ap-south-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t cluster .
      - docker tag cluster:latest 730365821560.dkr.ecr.ap-south-1.amazonaws.com/cluster:latest
     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 730365821560.dkr.ecr.ap-south-1.amazonaws.com/cluster:latest
      - echo Writing image definitions file...
      - printf '[{"name":"my-service","730365821560.dkr.ecr.ap-south-1.amazonaws.com/cluster:latest"}]' 730365821560.dkr.ecr.ap-south-1.amazonaws.com/cluster:latest > imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json
